In [51]:
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import classification_report

In [3]:
df = pd.read_csv('fake_or_real_news.csv')
df

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [5]:
X = df['text']
y = df.label

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [7]:
count_vectorizer = CountVectorizer(stop_words = 'english')

In [8]:
count_train = count_vectorizer.fit_transform(X_train, y_train)

In [9]:
count_test = count_vectorizer.transform(X_test)

In [10]:
print(count_vectorizer.get_feature_names()[:10])

['00', '000', '0000', '000000031', '00000031', '0001', '000billion', '000ft', '000km', '001']

In [17]:
count_df = pd.DataFrame(count_train.A, columns = count_vectorizer.get_feature_names())
count_df

,00,000,0000,000000031,00000031,0001,000billion,000ft,000km,001,...,שתי,תאמצנה,תוצאה,תחל,תיירות,תנותק,תעודת,תתרכז,القادمون,عربي
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4239,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4240,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4241,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4242,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df = 0.7)

In [13]:
tfidf_train = tfidf_vectorizer.fit_transform(X_train, y_train)

In [14]:
tfidf_test = tfidf_vectorizer.transform(X_test)

In [15]:
print(tfidf_vectorizer.get_feature_names()[:10])

['00', '000', '0000', '000000031', '00000031', '0001', '000billion', '000ft', '000km', '001']

In [16]:
print(tfidf_train.A[:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [20]:
tfidf_df = pd.DataFrame(tfidf_train.A, columns = tfidf_vectorizer.get_feature_names())
tfidf_df

,00,000,0000,000000031,00000031,0001,000billion,000ft,000km,001,...,שתי,תאמצנה,תוצאה,תחל,תיירות,תנותק,תעודת,תתרכז,القادمون,عربي
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4239,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4240,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4241,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4243,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
#  Calculate the difference in columns 

difference = set(count_df.columns) - set(tfidf_df.columns)
print(difference)

set()

In [22]:
# Check if the columns are equal

print(count_df.equals(tfidf_df))

False

In [24]:
nb_classifier = MultinomialNB()

In [25]:
nb_classifier.fit(count_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [27]:
pred = nb_classifier.predict(count_test)

In [33]:
score = metrics.accuracy_score(y_test, pred)
print(f'Accuracy Score: {score}')

Accuracy Score: 0.8885700621712099

In [34]:
cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
print(cm)

[[913 158]
 [ 75 945]]

In [40]:
print("Classification Report: \n {}"  .format(classification_report(y_test, pred, labels=["FAKE", "REAL"])))

Classification Report:
               precision    recall  f1-score   support

        FAKE       0.92      0.85      0.89      1071
        REAL       0.86      0.93      0.89      1020

    accuracy                           0.89      2091
   macro avg       0.89      0.89      0.89      2091
weighted avg       0.89      0.89      0.89      2091

In [36]:
#  Tfidf model

In [42]:
nb_classifier.fit(tfidf_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [43]:
pred_y = nb_classifier.predict(tfidf_test)

In [45]:
print(f'Accuracy Score: {metrics.accuracy_score(y_test, pred_y)}')

Accuracy Score: 0.8153993304638929

In [49]:
print(f'Confusion Matrix: \n {metrics.confusion_matrix(y_test, pred_y, labels=["FAKE", "REAL"])}')

Confusion Matrix:
 [[ 704  367]
 [  19 1001]]

In [47]:
print("Classification Report: \n {}".format(classification_report(y_test, pred_y, labels=["FAKE", "REAL"])))

Classification Report:
               precision    recall  f1-score   support

        FAKE       0.97      0.66      0.78      1071
        REAL       0.73      0.98      0.84      1020

    accuracy                           0.82      2091
   macro avg       0.85      0.82      0.81      2091
weighted avg       0.86      0.82      0.81      2091

In [54]:
#  Use different alpha 

alphas = np.arange(0, 1, 0.1)

def train_and_predict(alpha):
    nb_classifier.fit(tfidf_train, y_train)
    y_pred = nb_classifier.predict(tfidf_test)
    score = metrics.accuracy_score(y_test, y_pred)
    return score

for alpha in alphas:
    print('Alpha: ', alpha)
    print('Accuracy Score: ',  train_and_predict(alpha))
    print()

Alpha:  0.0
Accuracy Score:  0.8153993304638929

Alpha:  0.1
Accuracy Score:  0.8153993304638929

Alpha:  0.2
Accuracy Score:  0.8153993304638929

Alpha:  0.30000000000000004
Accuracy Score:  0.8153993304638929

Alpha:  0.4
Accuracy Score:  0.8153993304638929

Alpha:  0.5
Accuracy Score:  0.8153993304638929

Alpha:  0.6000000000000001
Accuracy Score:  0.8153993304638929

Alpha:  0.7000000000000001
Accuracy Score:  0.8153993304638929

Alpha:  0.8
Accuracy Score:  0.8153993304638929

Alpha:  0.9
Accuracy Score:  0.8153993304638929

In [55]:
class_labels = nb_classifier.classes_

In [56]:
feature_names = tfidf_vectorizer.get_feature_names()

In [58]:
feat_with_weights = sorted(zip(nb_classifier.coef_[0], feature_names))

In [59]:
# First 20 & last 20 class labels

print(class_labels[0], feat_with_weights[:20])
print(class_labels[1], feat_with_weights[-20:])

FAKE [(-11.322244731668087, '0001'), (-11.322244731668087, '000billion'), (-11.322244731668087, '000km'), (-11.322244731668087, '004s'), (-11.322244731668087, '00684'), (-11.322244731668087, '006s'), (-11.322244731668087, '007'), (-11.322244731668087, '007s'), (-11.322244731668087, '008s'), (-11.322244731668087, '0099'), (-11.322244731668087, '00am'), (-11.322244731668087, '00p'), (-11.322244731668087, '013c2812c9'), (-11.322244731668087, '014'), (-11.322244731668087, '016'), (-11.322244731668087, '01am'), (-11.322244731668087, '020'), (-11.322244731668087, '023'), (-11.322244731668087, '02714'), (-11.322244731668087, '028')]
REAL [(-7.732269536292581, 'states'), (-7.7054058282939355, 'rubio'), (-7.68695438202545, 'voters'), (-7.649203787194605, 'bush'), (-7.629791439102469, 'percent'), (-7.628368464993857, 'republicans'), (-7.592071649822604, 'house'), (-7.513175873902018, 'people'), (-7.5072746409547495, 'new'), (-7.482503832393821, 'party'), (-7.392735519270003, 'state'), (-7.371145741731472, 'cruz'), (-7.348773565909903, 'republican'), (-7.31165649290098, 'sanders'), (-7.304668755909965, 'president'), (-7.299626155313524, 'campaign'), (-7.101882275054515, 'obama'), (-6.740162424028141, 'clinton'), (-6.562399513905102, 'said'), (-6.324298680369767, 'trump')]